# -*- coding: utf-8 -*-
"""Python9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/127bA_ZD5A1DGacZyijKmAI4DPRmKYmKb
"""

import pandas as pd

"""Задача 40: Работать с файлом california_housing_train.csv, который находится в папке sample_data."""

df = pd.read_csv('sample_data/california_housing_train.csv')

df.head(2)

"""Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population)"""

df[df['population']>500]['median_house_value'].mean()

"""Задача 42: Узнать какая максимальная households в зоне минимального значения population"""

df[df['population'] == df['population'].min()]['households'].max()

"""Доп1 Показать среднее median_house_value, где households в зоне от среднего до максимального значения"""

df[(df['households'] > df['households'].mean()) & (df['households'] < df['households'].max())]['median_house_value'].mean()

"""Доп2 Вывести первые 5 строк таблицы, где median_house_value находится в диапазоне от 17000 до 265000 за исключением 180400"""

df[(df['median_house_value']>17000) & (df['median_house_value']<265000) & (df['median_house_value']!=180400)].head(5)